name: Development Push

on:
  push:
    branches:
      - develop

jobs:
  lint:
    uses: cosmicmind/actions/.github/workflows/lint-code.yml@release

  build:
    needs:
      - lint
    uses: cosmicmind/actions/.github/workflows/build-package.yml@release
    with:
      BUILD_TARGET: release
      NODE_ENV: production
      VITE_MODE: production

  test:
    needs:
      - build
    uses: cosmicmind/actions/.github/workflows/build-package.yml@release
    with:
      BUILD_TARGET: production
      NODE_ENV: production
      VITE_MODE: test

  codeql:
    needs:
      - test
    uses: cosmicmind/actions/.github/workflows/codeql.yml@release
