name: Feature Push

on:
  push:
    branches-ignore:
      - dev
      - release

jobs:
  lint:
    uses: cosmicverse/actions/.github/workflows/lint.yml@release
  codeql:
    needs: lint
    uses: cosmicverse/actions/.github/workflows/codeql.yml@release