name: Build and Tests

on:
  push:
    branches:    
      - '*'
      - '!main'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: cosmicverse/workflows/run-tests.yml@main
        