name: Release Package

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease'
        required: true

jobs:
  package-publish:
    uses: cosmicmind/github-actions/.github/workflows/package-publish.yml@main
    release-type: prerelease